<a href="https://colab.research.google.com/github/yuukimotai/AI_Master_Course/blob/main/simple_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

シンプルなディープラーニング



In [42]:
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()
print(iris.data[:10])
print(iris.target[:10])
print(iris.data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
[0 0 0 0 0 0 0 0 0 0]
(150, 4)


In [43]:
from sklearn import preprocessing
from keras import utils# これだけでOK

scaler = preprocessing.StandardScaler()
scaler.fit(iris.data)
x = scaler.transform(iris.data)

print(x[:10])

t = utils.to_categorical(iris.target)
print(t[:10])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [44]:
from sklearn.model_selection import train_test_split

x_train, x_test, t_train, t_test = train_test_split(x, t, train_size=0.75)

print(x_train)
print(x_train.shape)
print(x_test.shape)

[[-9.00681170e-01 -1.28296331e+00 -4.30827696e-01 -1.30754636e-01]
 [ 6.74501145e-01  3.28414053e-01  8.76433123e-01  1.44883158e+00]
 [ 2.49201920e+00  1.70959465e+00  1.50164482e+00  1.05393502e+00]
 [-7.79513300e-01 -8.22569778e-01  8.07091462e-02  2.64141916e-01]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.18381211e+00]
 [-2.94841818e-01 -1.31979479e-01  4.21733708e-01  3.95774101e-01]
 [ 3.10997534e-01 -5.92373012e-01  5.35408562e-01  8.77547895e-04]
 [ 2.24968346e+00 -1.31979479e-01  1.33113254e+00  1.44883158e+00]
 [ 4.32165405e-01 -5.92373012e-01  5.92245988e-01  7.90670654e-01]
 [ 5.53333275e-01 -3.62176246e-01  1.04694540e+00  7.90670654e-01]
 [ 3.10997534e-01 -1.31979479e-01  4.78571135e-01  2.64141916e-01]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.74885626e+00 -1.31979479e-01 -1.39706395e+00 -1.31544430e+00]
 [ 5.53333275e-01  5.58610819e-01  5.35408562e-01  5.27406285e-01]
 [-1.14301691e+00  1.24920112e+00 -1.34022653e+00 -1.44707648e

In [45]:
# モデルの構築
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential()
model.add(Dense(32, input_dim=4))
model.add(Activation("relu"))

#中間層
model.add(Dense(32))
model.add(Activation("relu"))

#最終層
model.add(Dense(3))
model.add(Activation("softmax"))

#コンパイル
model.compile(optimizer='sgd', loss='categorical_crossentropy',cloning=['accuracy'])

print(model.summary())

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_20 (Dense)            (None, 32)                160       
                                                                 
 activation_18 (Activation)  (None, 32)                0         
                                                                 
 dense_21 (Dense)            (None, 32)                1056      
                                                                 
 activation_19 (Activation)  (None, 32)                0         
                                                                 
 dense_22 (Dense)            (None, 3)                 99        
                                                                 
 activation_20 (Activation)  (None, 3)                 0         
                                                                 
Total params: 1315 (5.14 KB)
Trainable params: 1315 (5

In [70]:
# 学習
history = model.fit(x_train, t_train, epochs=30, batch_size=8)
print(history.history.values())


Epoch 1/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0819
Epoch 2/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0822
Epoch 3/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0812
Epoch 4/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0818
Epoch 5/30
14/14 [==============================] - 0s 4ms/step - loss: 0.0807
Epoch 6/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0807
Epoch 7/30
14/14 [==============================] - 0s 4ms/step - loss: 0.0809
Epoch 8/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0800
Epoch 9/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0801
Epoch 10/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0798
Epoch 11/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0788
Epoch 12/30
14/14 [==============================] - 0s 3ms/step - loss: 0.0794
Epoch 13/30
14/14 [==============================

In [68]:
#学習の推移
import matplotlib.pyplot as plt
print(history.history.keys())

hist_loss = history.history["loss"]
#hist_acc = history.history["accuracy"]

#plt.plot(np.arrange(len(hist_loss)), hist_loss, label="loss")
#plt.plot(np.arrange(len(hist_acc)), hist_acc, label="acc")
# plt.legend()
# plt.show()

dict_keys(['loss'])
